### ISSUE TITLE
Docker instance updated and gave 'Spotweb contains updated global settings settings. Please run 'bin/upgrade-db.php' from a console window '

### ISSUE THREAD

**Issue by MrHappy** [jgeusebroek/docker-spotweb#51]
When I run the command I get the following:
```
bin/upgrade-db.php
Updating schema..(pdo_mysql)
	Validating spots(messageid)
	Validating spots(poster)
	Validating spots(title)
	Validating spots(tag)
	Validating spots(category)
	Validating spots(subcata)
	Validating spots(subcatb)
	Validating spots(subcatc)
	Validating spots(subcatd)
	Validating spots(subcatz)
	Validating spots(stamp)
	Validating spots(reversestamp)
	Validating spots(filesize)
	Validating spots(moderated)
	Validating spots(commentcount)
	Validating spots(spotrating)
	Validating spots(reportcount)
	Validating spots(spotterid)
	Validating spots(editstamp)
	Validating spots(editor)
	Validating spotsfull(messageid)
	Validating spotsfull(verified)
	Validating spotsfull(usersignature)
	Validating spotsfull(userkey)
	Validating spotsfull(xmlsignature)
	Validating spotsfull(fullxml)


SpotWeb crashed

Database schema or settings upgrade failed:
   Invalid collation setting for varchar: utf8mb3_general_ci


#0 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(200): SpotStruct_mysql->getColumnInfo()
#1 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(182): SpotStruct_abs->compareColumn()
#2 /var/www/spotweb/lib/dbstruct/SpotStruct_abs.php(412): SpotStruct_abs->validateColumn()
#3 /var/www/spotweb/lib/services/Upgrade/Services_Upgrade_Base.php(56): SpotStruct_abs->updateSchema()
#4 /var/www/spotweb/bin/upgrade-db.php(55): Services_Upgrade_Base->database()
```

What do I need to fix? Nothing else changed...

**Comment by jgeusebroek** [comment]
Looks like your database version isn't supported. What MySQL of MariaDB are you using? This more a spotweb issue than an issue with the docker image.

**Comment by MrHappy** [comment]
Some columns are/were in utf8mb3. After changing them to utf8mb4 it went along.
